/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.gosun.servicemonitor.rpc;

@SuppressWarnings("all")
/** MonitorClientInterface */
@org.apache.avro.specific.AvroGenerated
public interface MonitorClientInterface {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MonitorClientInterface\",\"namespace\":\"com.gosun.servicemonitor.rpc\",\"doc\":\"MonitorClientInterface\",\"types\":[{\"type\":\"record\",\"name\":\"Info\",\"fields\":[{\"name\":\"sendTime\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"RpcEnv\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"Response\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"QTime\",\"type\":\"long\"},{\"name\":\"msg\",\"type\":\"string\"}]}],\"messages\":{\"activate\":{\"doc\":\"activate node\",\"request\":[{\"name\":\"rpcEnv\",\"type\":\"RpcEnv\"},{\"name\":\"info\",\"type\":\"Info\"}],\"response\":\"Response\"}}}");
  /** activate node */
  com.gosun.servicemonitor.rpc.Response activate(com.gosun.servicemonitor.rpc.RpcEnv rpcEnv, com.gosun.servicemonitor.rpc.Info info) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** MonitorClientInterface */
  public interface Callback extends MonitorClientInterface {
    public static final org.apache.avro.Protocol PROTOCOL = com.gosun.servicemonitor.rpc.MonitorClientInterface.PROTOCOL;
    /** activate node */
    void activate(com.gosun.servicemonitor.rpc.RpcEnv rpcEnv, com.gosun.servicemonitor.rpc.Info info, org.apache.avro.ipc.Callback<com.gosun.servicemonitor.rpc.Response> callback) throws java.io.IOException;
  }
}