/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.gosun.servicemonitor.rpc;

@SuppressWarnings("all")
/** MonitorCentreInterface */
@org.apache.avro.specific.AvroGenerated
public interface MonitorCentreInterface {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MonitorCentreInterface\",\"namespace\":\"com.gosun.servicemonitor.rpc\",\"doc\":\"MonitorCentreInterface\",\"types\":[{\"type\":\"record\",\"name\":\"Info\",\"fields\":[{\"name\":\"sendTime\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Heartbeat\",\"fields\":[{\"name\":\"extraMsg\",\"type\":\"string\"},{\"name\":\"nodeId\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Node\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"role\",\"type\":\"string\"},{\"name\":\"note\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Servicer\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"note\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"RpcEnv\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"Response\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"QTime\",\"type\":\"long\"},{\"name\":\"msg\",\"type\":\"string\"}]}],\"messages\":{\"sendHeartbeat\":{\"doc\":\"Send Heartbeat Request.\",\"request\":[{\"name\":\"heartbeat\",\"type\":\"Heartbeat\"},{\"name\":\"info\",\"type\":\"Info\"}],\"response\":\"Response\"},\"registerNode\":{\"doc\":\"Register Node Request.\",\"request\":[{\"name\":\"rpcEnv\",\"type\":\"RpcEnv\"},{\"name\":\"node\",\"type\":\"Node\"},{\"name\":\"servicer\",\"type\":\"Servicer\"},{\"name\":\"info\",\"type\":\"Info\"}],\"response\":\"Response\"}}}");
  /** Send Heartbeat Request. */
  com.gosun.servicemonitor.rpc.Response sendHeartbeat(com.gosun.servicemonitor.rpc.Heartbeat heartbeat, com.gosun.servicemonitor.rpc.Info info) throws org.apache.avro.AvroRemoteException;
  /** Register Node Request. */
  com.gosun.servicemonitor.rpc.Response registerNode(com.gosun.servicemonitor.rpc.RpcEnv rpcEnv, com.gosun.servicemonitor.rpc.Node node, com.gosun.servicemonitor.rpc.Servicer servicer, com.gosun.servicemonitor.rpc.Info info) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** MonitorCentreInterface */
  public interface Callback extends MonitorCentreInterface {
    public static final org.apache.avro.Protocol PROTOCOL = com.gosun.servicemonitor.rpc.MonitorCentreInterface.PROTOCOL;
    /** Send Heartbeat Request. */
    void sendHeartbeat(com.gosun.servicemonitor.rpc.Heartbeat heartbeat, com.gosun.servicemonitor.rpc.Info info, org.apache.avro.ipc.Callback<com.gosun.servicemonitor.rpc.Response> callback) throws java.io.IOException;
    /** Register Node Request. */
    void registerNode(com.gosun.servicemonitor.rpc.RpcEnv rpcEnv, com.gosun.servicemonitor.rpc.Node node, com.gosun.servicemonitor.rpc.Servicer servicer, com.gosun.servicemonitor.rpc.Info info, org.apache.avro.ipc.Callback<com.gosun.servicemonitor.rpc.Response> callback) throws java.io.IOException;
  }
}