/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.gosun.servicemonitor.rpc;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Servicer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Servicer\",\"namespace\":\"com.gosun.servicemonitor.rpc\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"note\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence note;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Servicer() {}

  /**
   * All-args constructor.
   */
  public Servicer(java.lang.CharSequence name, java.lang.CharSequence note) {
    this.name = name;
    this.note = note;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return note;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: note = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'note' field.
   */
  public java.lang.CharSequence getNote() {
    return note;
  }

  /**
   * Sets the value of the 'note' field.
   * @param value the value to set.
   */
  public void setNote(java.lang.CharSequence value) {
    this.note = value;
  }

  /** Creates a new Servicer RecordBuilder */
  public static com.gosun.servicemonitor.rpc.Servicer.Builder newBuilder() {
    return new com.gosun.servicemonitor.rpc.Servicer.Builder();
  }
  
  /** Creates a new Servicer RecordBuilder by copying an existing Builder */
  public static com.gosun.servicemonitor.rpc.Servicer.Builder newBuilder(com.gosun.servicemonitor.rpc.Servicer.Builder other) {
    return new com.gosun.servicemonitor.rpc.Servicer.Builder(other);
  }
  
  /** Creates a new Servicer RecordBuilder by copying an existing Servicer instance */
  public static com.gosun.servicemonitor.rpc.Servicer.Builder newBuilder(com.gosun.servicemonitor.rpc.Servicer other) {
    return new com.gosun.servicemonitor.rpc.Servicer.Builder(other);
  }
  
  /**
   * RecordBuilder for Servicer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Servicer>
    implements org.apache.avro.data.RecordBuilder<Servicer> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence note;

    /** Creates a new Builder */
    private Builder() {
      super(com.gosun.servicemonitor.rpc.Servicer.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.gosun.servicemonitor.rpc.Servicer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.note)) {
        this.note = data().deepCopy(fields()[1].schema(), other.note);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Servicer instance */
    private Builder(com.gosun.servicemonitor.rpc.Servicer other) {
            super(com.gosun.servicemonitor.rpc.Servicer.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.note)) {
        this.note = data().deepCopy(fields()[1].schema(), other.note);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.gosun.servicemonitor.rpc.Servicer.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.gosun.servicemonitor.rpc.Servicer.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'note' field */
    public java.lang.CharSequence getNote() {
      return note;
    }
    
    /** Sets the value of the 'note' field */
    public com.gosun.servicemonitor.rpc.Servicer.Builder setNote(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.note = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'note' field has been set */
    public boolean hasNote() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'note' field */
    public com.gosun.servicemonitor.rpc.Servicer.Builder clearNote() {
      note = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Servicer build() {
      try {
        Servicer record = new Servicer();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.note = fieldSetFlags()[1] ? this.note : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
